onnx_model_path = "onnx_models/yolov5n_head.onnx"
visualize = true
out_img_path = "out_images"
source = "webcam" # webcam for webcam, or path to video

[input_data]
imgsz = 320

[predictor]
conf_thres = 0.25
iou_thres = 0.45
classes = []