onnx_model_path = "onnx_models/yolov5n.onnx"
visualize = true
out_img_path = "out_images"
val_data_path = "coco128"
inf_exec = "fpga" # cpu or fpga
source = "webcam" # webcam for webcam, or path to video
#source = "input_video/v_Biking_g23_c03.avi"

[input_data]
imgsz = 320

[predictor]
conf_thres = 0.25
iou_thres = 0.5
classes = []

[hardware]
bitstream_path = "hardware/amd-openhw-23-zcu106.bit"
weights_lookup_table = "weight-lookup.json"
weights_path = "weights"

